on:
  # cron job per day
  # schedule:
    # - cron: "0 0 * * *"
  # manual trigger
  workflow_dispatch:
name: Create SQLite database
jobs:
  sqlite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.3.0
      - name: Install
        run: pnpm install
      - name: Run genreate sqlite action
        run: 
          node ./generate-sqlite.mjs
      - name: Draft Release
        id: create_release
        uses: voxelum/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: v${{ github.run_number }}
          draft: false
          prerelease: false
          body: v${{ github.run_number }}
          asset_dir_path: ./build
